### ISSUE TITLE
Recreate Schema

### ISSUE THREAD

**Issue by humayunk** [humayunk/chefspace#6]
![Image](https://github.com/humayunk/chefspace/assets/166848018/14332fb1-8b1e-4a68-a9a7-5147daa43df0)

https://kitt.lewagon.com/db/128125

**Comment by humayunk** [comment]
@VaedaSolomon @Jeffryaime @juliettehutton added the schema, we're just confirming how to handle the images

**Comment by juliettehutton** [comment]
![Image](https://github.com/humayunk/chefspace/assets/166848018/bae24488-8cd1-48d7-9a49-7e0236545933)

updated schema, no need for picture fields as it will be user uploaded
